### ISSUE TITLE
_layouts/home.html missing

### ISSUE THREAD

**Issue by davidljung** [mmistakes/skinny-bones-jekyll#20]
Hello.  The http://mmistakes.github.io/skinny-bones-jekyll/getting-started/ page has a Scaffolding section that shows a home.html layout, but it doesn't existing in the download or on github.  Could you please include it (unless it has been depreciated).

I'm just getting started with Jekyll and Skinny-Bones and it would hep enormously helpful if there were some example page & article sources.  For example, the source for Skinny-Bones site or just the Sample Articles would be really helpful.

Thanks!

**Comment by mmistakes** [comment]
It's in the gh-pages branch. Was just a quick layout I used for the demo site that I didn't feel was ready for prime time so it's not in master. 

Sample articles are in the branch as well as not to junk up master since they should be removed anyways.
