### ISSUE TITLE
Octopress doesn't work after following recommended install procedure

### ISSUE THREAD

**Issue by vperic** [mmistakes/skinny-bones-jekyll#22]
I'm not sure what is going on here, everything worked fine back in December. I'm a complete beginner in Ruby packaging, so I wondered if you could lend me a hand. I kept getting errors so I uninstalled all my gems and then followed the suggested installation procedure (using bundler). If I then try to do something like `octopress new post "asdf"`, I get:

```
octopress 3.0.0.rc.34 | Error:  undefined method `require_from_bundler' for Jekyll::PluginManager:Class
```
If I try doing `gem install jekyll`, it installs a newer version (2.5.3 currently) than specified, so then I get different errors:

```
vperic@vperic-laptop:~/devel/ossicz-sajt> octopress new post "asdf"
/usr/lib64/ruby/gems/1.9.1/gems/jekyll-2.5.3/lib/jekyll/plugin_manager.rb:29:in `require': cannot load such file -- jekyll-sitemap (LoadError)
        from /usr/lib64/ruby/gems/1.9.1/gems/jekyll-2.5.3/lib/jekyll/plugin_manager.rb:29:in `block in require_gems'
        from /usr/lib64/ruby/gems/1.9.1/gems/jekyll-2.5.3/lib/jekyll/plugin_manager.rb:26:in `each'
        from /usr/lib64/ruby/gems/1.9.1/gems/jekyll-2.5.3/lib/jekyll/plugin_manager.rb:26:in `require_gems'
        from /usr/lib64/ruby/gems/1.9.1/gems/jekyll-2.5.3/lib/jekyll/plugin_manager.rb:19:in `conscientious_require'
        from /usr/lib64/ruby/gems/1.9.1/gems/octopress-3.0.0.rc.34/lib/octopress.rb:69:in `read_site'
        from /usr/lib64/ruby/gems/1.9.1/gems/octopress-3.0.0.rc.34/lib/octopress.rb:60:in `site'
        from /usr/lib64/ruby/gems/1.9.1/gems/octopress-3.0.0.rc.34/lib/octopress/commands/new.rb:52:in `block (3 levels) in init_with_program'
        from /usr/lib64/ruby/gems/1.9.1/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `call'
        from /usr/lib64/ruby/gems/1.9.1/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `block in execute'
        from /usr/lib64/ruby/gems/1.9.1/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `each'
        from /usr/lib64/ruby/gems/1.9.1/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `execute'
        from /usr/lib64/ruby/gems/1.9.1/gems/mercenary-0.3.5/lib/mercenary/program.rb:42:in `go'
        from /usr/lib64/ruby/gems/1.9.1/gems/mercenary-0.3.5/lib/mercenary.rb:19:in `program'
        from /usr/lib64/ruby/gems/1.9.1/gems/octopress-3.0.0.rc.34/bin/octopress:16:in `<top (required)>'
        from /usr/bin/octopress:23:in `load'
        from /usr/bin/octopress:23:in `<main>'
```

I assume this is because I'm running a newer Jekyll than your site specifies. Still, I reproduce the first error by running eg. `bundle exec octopress new post "asdf"`.

I realize that using octopress is not really obligatory, I just remember it as a neat tool, plus I can't be sure that something else isn't broken (though currently building and serving the site works fine).

Thanks in advance!

**Comment by mmistakes** [comment]
Try `bundle update` and it will update all of the gems currently referenced in your `Gemfile.lock`. The should hopefully get it back to working for you.

I know I recently upgraded something and had troubles myself. But that could have been from trying out the Jekyll 3 beta which caused some problems with gems that weren't updated to support it yet.

**Comment by vperic** [comment]
Nope, errors are the same.

**Comment by mmistakes** [comment]
I'm out of ideas then. have you tried leaving an issue on the Octopress repo? I didn't write the gem so I don't really know much about it except the basics, and I'm far from a Ruby expert.

**Comment by milas** [comment]
I just ran into this same issue -- the solution is to use `bundle exec`, e.g.:

```
bundle exec octopress new post "asdf"
```

Hope this helps someone!

**Comment by mmistakes** [comment]
That's correct @milas. When in doubt always run Jekyll and/or Octopress with `bundle exec`. It forces all the correct versions of the various gems to load which should with any errors experienced.
