### ISSUE TITLE
Having trouble installing to github pages

### ISSUE THREAD

**Issue by twhite96** [mmistakes/skinny-bones-jekyll#26]
Installed dependencies, downloaded the file, etc but using rake to switch themes is not working. Any suggestions?

**Comment by twhite96** [comment]
I try to install with git cloning with the rake command and I get this error: 

rake aborted!
Errno::ENOENT: No such file or directory @ rb_sysopen - ./_theme_packages/hello/manifest.yml
/Users/tiffanywhite/Desktop/Git Repositories/twhite96.github.io/Rakefile:289:in `initialize'
/Users/tiffanywhite/Desktop/Git Repositories/twhite96.github.io/Rakefile:289:in `open'
/Users/tiffanywhite/Desktop/Git Repositories/twhite96.github.io/Rakefile:289:in `verify_manifest'
/Users/tiffanywhite/Desktop/Git Repositories/twhite96.github.io/Rakefile:188:in `block (2 levels) in <top (required)>'
/Users/tiffanywhite/.rvm/gems/ruby-2.1.5/bin/ruby_executable_hooks:15:in `eval'
/Users/tiffanywhite/.rvm/gems/ruby-2.1.5/bin/ruby_executable_hooks:15:in `<main>'

Any ideas?

**Comment by twhite96** [comment]
No manifest.yml file so it is having a fit. I can't find it in the zip file I downloaded. Any chance you can add one?

**Comment by mmistakes** [comment]
There is no rake task to switch themes.  You have to manually copy in all of the theme files if you're switching from an existing theme. On the demo site there's a list of all the layouts, includes, and assets you'll need. 

I think Jekyll bootstrap themes and Octopress themes use rake so maybe that's were the confusion is. This is just a vanilla Jekyll repo with some basic setup and styling done to build off of.
