### ISSUE TITLE
disqus is not work

### ISSUE THREAD

**Issue by awong1900** [mmistakes/skinny-bones-jekyll#33]
In the sample, the disqus is not work.

**Comment by mmistakes** [comment]
Was using the wrong variable in `comments.html` include. [Here's the fix](https://github.com/mmistakes/skinny-bones-jekyll/commit/10b7dd7fe7b761c499b5058e00614446ef039288) or just pull the latest commit.

**Comment by awong1900** [comment]
well done. This is excellent  jekyll site.

**Comment by Ladvien** [comment]
Also, a tab needs to be added in _config.yml to make the disqus-shortname variables a sub-property of site.owner.

owner:
...
->disqus-shortname:
