### ISSUE TITLE
Home layout

### ISSUE THREAD

**Issue by OdysLam** [mmistakes/skinny-bones-jekyll#40]
I am actually a noobie to the whole Jekyll area,and new to programming in general so bare with me.
I am trying to find the home layout that it  is supposed(according to the index at your site)  to exist but i can't find it. I want a homepage like (http://mmistakes.github.io/skinny-bones-jekyll/) in the original site and not an archive as a homepage, is that doable?
Thank you for your time

**Comment by mmistakes** [comment]
Yes that's doable. Check the gh-pages branch of the Skinny Bones repo to see how I did the homepage that isn't an archive layout.

**Comment by OdysLam** [comment]
Yeah , as i told you i am new in github, so it took me some time to discover that there are branches and what branches are etc ,etc.
In the end i found it and applied to my site, thank you for your swift response(i read it as soon as you posted it ) and sorry for my late reply.
Cheers :)
