### ISSUE TITLE
Simple post not showing up

### ISSUE THREAD

**Issue by emilydonovan** [mmistakes/skinny-bones-jekyll#41]
I tried making a simple post: [_posts/2015-08-02-giraffe.md](https://github.com/emilydonovan/emilydonovan.github.io/blob/master/_posts/2015-08-02-giraffe.md) and it is not showing up on my page (emilydonovan.github.io). All I put in the YAML front matter is the layout and title. That is the only file I have added/changed so far so I'm confused as to why it's not showing on the up.

**Comment by mmistakes** [comment]
What does it do when built locally?

**Comment by mmistakes** [comment]
If you're still having this issue please reopen and provide more detail.
