### ISSUE TITLE
specific teaser image not showing

### ISSUE THREAD

**Issue by adeldaoud** [mmistakes/skinny-bones-jekyll#44]
Hi

A simple question. I want to add a specific image for the blog posts and added therefore a “teaser:” in the front matter. Like this:

---
layout: article
title: "At the School"
categories: articles
modified: 2015-08-27T11:57:41-04:00
tags: [sample]
comments: false
ads: false
teaser: nssr.jpg
image:
  feature: nssr.jpg
---

The default teaser is appearing though. Any ideas what is wrong?

**Comment by mmistakes** [comment]
Your YAML is incorrect. `teaser` and `feature` have to be indented below `image`. For example like this.

```
image:
  teaser: teaser.jpg
  feature: feature.jpg
```

Take a look at the [sample posts](https://github.com/mmistakes/skinny-bones-jekyll/blob/gh-pages/_posts/articles/2013-05-23-readability-feature-post.md) in the `gh-pages` examples to see how I did it for the demo site.
