### ISSUE TITLE
adding Google Analytics

### ISSUE THREAD

**Issue by wgoh** [mmistakes/skinny-bones-jekyll#55]
Hi all,

I am new to Jekyll + Skinny Bones and I would like to ask how do I add Google Analytics tracking to my website?

Thank you very much.

**Comment by mmistakes** [comment]
1. Copy the snippet Google Analytics gives you for tracking
2. Paste that `<script>` into the [`default.html`](https://github.com/mmistakes/skinny-bones-jekyll/blob/master/_layouts/default.html) layout somewhere... I'd suggest at the bottom after the other scripts.

You could also put the GA script inside of `main.js` if you prefer to keep them together. It's really up to you and how you like to work.
