### ISSUE TITLE
Jekyll 3 now supported by GH Pages

### ISSUE THREAD

**Issue by Sotiris-k** [mmistakes/skinny-bones-jekyll#56]
According to [this](https://github.com/blog/2100-github-pages-now-faster-and-simpler-with-jekyll-3-0)  article, GH Pages now supports Jekyll 3. Maybe make the jekyll3 branch to master now?

**Comment by mmistakes** [comment]
Yes saw this earlier. Plan to merge that branch as soon as I have time to double check everything.
