### ISSUE TITLE
custom 404

### ISSUE THREAD

**Issue by maxheld83** [mmistakes/skinny-bones-jekyll#61]
I love the (custom) 404 pages in your other themes, wondering how hard it would be to add that here ...

**Comment by mmistakes** [comment]
It should be fairly trivial for you to take the 404 page from any of my other themes and repurpose it here. It's just a standard page with a Google script added to take care of the search box. Might need some CSS but the pieces are there.

**Comment by maxheld83** [comment]
thanks, great!
