### ISSUE TITLE
disable page open animation

### ISSUE THREAD

**Issue by maxheld83** [mmistakes/skinny-bones-jekyll#62]
I really like the subtle animations throughout the theme.

I'd like to disable the animation on page open, though.

Is there an elegant simple way to disable this?

**Comment by mmistakes** [comment]
I'm pretty sure the only animations used are for the overlay menu that slides in on click. Unless I'm completely delusional there shouldn't be any sort of page open animation. I have one on my personal site but not on the theme.

If you want to remove animations they're all done via CSS. Look for declarations that start with `transition:`, those set the type of easing and the duration between states. If that's removed it won't tween the states and you'll just get a static cut without the smoothness between.

**Comment by maxheld83** [comment]
It's very possible that *I* am delusional, and I can't seem to be able to reproduce this reliably, but sometimes when I *refresh* (though not open) a page on http://www.maxheld.de it looks the like the main body is being squeezed in from the top left corner in both safari and chrome.

The transitions, as you point out, all seem to refer to the overlay on click.

**Comment by mmistakes** [comment]
I don't think it's an animation doing that. Most likely it's the page
loading and/or an image that pushes the content out as it comes in. Giving
the impression things are moving.

**Comment by maxheld83** [comment]
hehe, that's funny. Makes sense
