### ISSUE TITLE
Teaser images in sharing

### ISSUE THREAD

**Issue by michaellevy** [mmistakes/skinny-bones-jekyll#65]
Michael, I'm sorry to have to bother you with this, but I can't get teaser images to show up right in Twitter or Facebook. I notice the sharing links don't show up at all on the skinny-bones demo site. On mine Twitter Cards will appear, but with either the default site teaser or Twitter's no-image image, and the default shows up on Facebook. It's working fine at mademistakes.com, and _includes/open-graph.html is the same there, and the issue isn't in _includes/share-this.html as far as I can tell. Any ideas?

**Comment by mmistakes** [comment]
Are you certain you've assigned a feature image to a post? The large summary Twitter card meta pulls in `page.image.feature`. If you don't have something like:

```yaml
image:
  feature: your-large-feature-image.jpg
```

Then it falls back to using whatever the `site.logo` in `_config.yml` is.

For example one of the [sample media posts](https://mmistakes.github.io/skinny-bones-jekyll/media/sample-media-page/) on the demo site shows this as it's Twitter card.

![screen shot 2016-04-29 at 11 20 53 pm](https://cloud.githubusercontent.com/assets/1376749/14933599/874da326-0e61-11e6-8f49-fb6c31c766dc.png)

Also if you happened to test a page with Twitter either by tweeting it or the [card validator](https://cards-dev.twitter.com/validator) site it's likely been cached. If you change it and test again it doesn't always act like it's been updated. I don't know if there's a way to force Twitter to rescrape the page like Facebook's [Open Graph debugger](https://developers.facebook.com/tools/debug/).

In my experience social sharing has been a mixed bag when it comes to Twitter, Facebook, or Pinterest properly pulling in the correct images and meta info. Images can be particularly dicey if you don't have them sized in the correct proportions and minimum sizes. Check the dev sites as they specifically outline the requirements.

**Comment by michaellevy** [comment]
Ah, I had teaser and feature images mixed up. I don't much use feature images, but changing the two references to page.image.feature in open-graph.html to to page.image.teaser produces the behavior I wanted. Thanks so much!
