### ISSUE TITLE
Content below post-grid sucked into grid

### ISSUE THREAD

**Issue by michaellevy** [mmistakes/skinny-bones-jekyll#66]
Anything below my blog tiles gets sucked into whatever width is left after the last tile. Is there a way to add content below the grid? Thanks.

![screen shot 2016-04-30 at 9 53 10 am](https://cloud.githubusercontent.com/assets/4422055/14937343/6d85e914-0eb9-11e6-9c22-9e58c79ee326.png)

**Comment by mmistakes** [comment]
You need to properly clear the teasers in the grid as they are they have `float: left;` set in the CSS.

Closed issue #54 is related and might point you in the right direction.

**Comment by michaellevy** [comment]
Thank you. It was as easy as adding `<div style="clear: both;"></div>` between the grid and next section.
