### ISSUE TITLE
Pagination?

### ISSUE THREAD

**Issue by varmint09** [mmistakes/skinny-bones-jekyll#70]
Hello,

I only want to show six posts at a time on the homepage, how can I paginate this?

I use the following display code;

    <div class="row">
    {% for post in site.posts %}
        {% include post-grid.html %}
    {% endfor %}
    </div>

and this is the post...

    <div class="col-xs-12 col-md-4 post" itemscope itemtype="http://schema.org/Article">
        <h2><a href="{{ site.url }}{{ post.url }}">{{ post.title }}</a></h2>
    </div>

I want to show 6 at a time and then some basic bootstrap style pagination.

Can anyone help?

**Comment by mmistakes** [comment]
You'll have to install and [setup](https://jekyllrb.com/docs/pagination/) the [`jekyll-paginate`](https://github.com/jekyll/jekyll-paginate) plugin to do this.

Check out some of my other themes if you want examples of how to code it as they support pagination out of the box.

- [Minimal Mistakes](https://github.com/mmistakes/minimal-mistakes)
- [HPSTR](https://github.com/mmistakes/hpstr-jekyll-theme)
