### ISSUE TITLE
May support markdown tilde '~' ?

### ISSUE THREAD

**Issue by awong1900** [mmistakes/skinny-bones-jekyll#71]
like this:
![image](https://cloud.githubusercontent.com/assets/4022612/16223114/5e904a06-37ce-11e6-8a31-40e5ea028fc8.png)

**Comment by mmistakes** [comment]
Whether a Markdown parser supports `~` strikethroughs depends. Jekyll ships with [Kramdown](http://kramdown.gettalong.org/) as the default. You can change to another one that possibly supports it.

Closing because this isn't a theme issue.

**Comment by awong1900** [comment]
thx
