### ISSUE TITLE
could I change the locales dynamicly on the page?

### ISSUE THREAD

**Issue by lhf552004** [mmistakes/skinny-bones-jekyll#73]
I want to implement the language changing function on my blog site. But the table list and other in the *.yml cannot change the text.

**Comment by mmistakes** [comment]
My solution is only to localize text into 1 language. If you want to provide multiple versions of translated content you'll need to build a [more robust solution](https://www.sylvaindurand.org/making-jekyll-multilingual/).

There are also Jekyll plugins out there to help with this, but they don't work with GitHub Pages if you're hosting there.

- [jekyll-localization](https://github.com/prometheus-ev/jekyll-localization)
- [jekyll-multiple-languages-plugin](https://github.com/Anthony-Gaudino/jekyll-multiple-languages-plugin)

**Comment by lhf552004** [comment]
Thank you. I get it.. I prefer the Multilingual Jekyll. The solution is simliar with our application, using ref.
