### ISSUE TITLE
https: problem with certificate

### ISSUE THREAD

**Issue by ikashnitsky** [mmistakes/skinny-bones-jekyll#80]
There are some problems with certificates in a freshly forked version of a website
https://ikashnitsky.github.io/
I checked "Enforce HTTPS" in the repository settings.
Please, help me solve the issue. 
Note, there is no such problem for the [example site](https://mmistakes.github.io/skinny-bones-jekyll/)

**Comment by mmistakes** [comment]
In your **_config.yml** you need to set `site.url` to the `https` version of your domain like this:

```yaml
url: https://ikashnitsky.github.io
```

Looking at your site source all the CSS and JS are loading `http://` versions which will be blocked when trying to access your site securely. The browser won't load mixed content in this way.

**Comment by ikashnitsky** [comment]
Oh, thanks a lot!
Sorry, I'm still a complete newb
