### ISSUE TITLE
error GitHub Pages: docs/css/main.scss has an error on line 10

### ISSUE THREAD

**Issue by CisSasGot** [mmistakes/skinny-bones-jekyll#82]
Hello
I want to use this template to build a page github, I acted step-by-step instructions at: https://mmistakes.github.io/skinny-bones-jekyll/getting-started/ , but it works only locally.
Github reports an error that I do not know how to jump?

###  **THIS ERROR:**  **Your site is having problems building: Your SCSS file docs/css/main.scss has an error on line 10: File to import not found or unreadable: variables. Load path: /hoosegow/.bundle/ruby/2.3.0/gems/jekyll-theme-primer-0.1.5/_sass. For more information, see https://help.github.com/articles/page-build-failed-invalid-sass-or-scss/.**

Please help me

**Comment by mmistakes** [comment]
Do you have a link to a public repo I could take a look and see if something else stands out to me. Without an example all I can do is speculate.

If I had to guess you're using GitHub Pages to host a site off the `master` branch using the `docs` folder right? From that error seems to me you're missing some of the Sass partials that are in `_sass` and that's what the error is all about.

That or you have some bad code in one of the files.

When you build locally are you using the [`github-pages` gem](https://help.github.com/articles/setting-up-your-github-pages-site-locally-with-jekyll/) or vanilla `jekyll`? The former mimics GH Pages and will make troubleshooting easier. Using the vanilla Jekyll gem won't likely show you the same errors as the version could be different and GH locks various settings.

**Comment by SLTTL** [comment]
What was the solution? I am getting the same error
