### ISSUE TITLE
Disqus does not load

### ISSUE THREAD

**Issue by ikashnitsky** [mmistakes/skinny-bones-jekyll#85]
I'm sorry to bother if it's something on my side; but I failed to fix it myself. 
Disqus fails on [my website](https://ikashnitsky.github.io/2017/gender-gap-in-swedish-mortality/). 
>We were unable to load Disqus.  

What can be the cause?

**Comment by mmistakes** [comment]
Looks like something on your end. Sure you have your Disqus account setup properly and using the correct `shortname` in the theme?

The script is loading and is activated correctly in the theme so that's not the issue. Something is up with Disqus and/or your account setup.

**Comment by ikashnitsky** [comment]
Finally, fixed it. Sorry, my stupidity. The problem was indeed with `disqus-shortname`: I did not grasp from the beginning that it is a site-specific value, not my login at Disqus.
Maybe worth adding a couple of lines to the [getting started](https://mmistakes.github.io/skinny-bones-jekyll/getting-started/) page or as a short post [here ](https://mmistakes.github.io/skinny-bones-jekyll/articles/)?

**Comment by mmistakes** [comment]
Happy to accept a pull request if you want to take a stab at improving the documentation.

**Comment by ikashnitsky** [comment]
I'd like to. The problem is, I don't know where the code for the Skinny Bones demo lies. [This repo](https://github.com/mmistakes/skinny-bones-jekyll) is stripped down.

**Comment by mmistakes** [comment]
Flip to the `gh-pages` branch. It's all there... https://github.com/mmistakes/skinny-bones-jekyll/tree/gh-pages
